# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci=list()
fibonacci.append(1)
fibonacci.append(2)
i=2

while True:
    if fibonacci[i-1]+fibonacci[i-2] <4000000:
        fibonacci.append(fibonacci[i-1]+fibonacci[i-2])
        i+=1
    else:
        break

toplam=0

for k in fibonacci:
    if k%2==0:
        toplam+=k



print(toplam)